### ISSUE TITLE
i386 Rusdesk build for Linux is not supported by mouce >>>>"expected u32, found u64"

### ISSUE THREAD

**Issue by bykovo** [emrebicer/mouce#13]
Compiling clang-sys v1.3.3
error[E0308]: mismatched types
--> /root/.cargo/git/checkouts/mouce-da81cbdbeafc6640/26da8d4/src/nix/uinput.rs:186:23
|
186 | ioctl(fd, UI_DEV_DESTROY as u64);
| ^^^^^^^^^^^^^^^^^^^^^ expected u32, found u64
|
help: you can convert a u64 to a u32 and panic if the converted value doesn't fit
|
186 | ioctl(fd, (UI_DEV_DESTROY as u64).try_into().unwrap());
| + +++++++++++++++++++++

For more information about this error, try rustc --explain E0308.
error: could not compile mouce due to previous error

**Comment by emrebicer** [comment]
This issue was already fixed with #10 . After this merge I can compile for 32 bit systems. It looks like you are referencing to and old version of the project, can you clone from the master branch and try again with latest version?

**Comment by emrebicer** [comment]
Closing the issue due to inactivity.
