### ISSUE TITLE
Bug when uinput setup

### ISSUE THREAD

**Issue by fufesou** [emrebicer/mouce#6]
[`name`](https://github.com/emrebicer/mouce/blob/7febd2505662c6a3424a389aba52700aa0fff61b/src/nix/uinput.rs#L246)  field in `struct UInputSetup` has incorrect type.

``` rust
/// uinput types
#[repr(C)]
struct UInputSetup {
    id: InputId,
    name: CString,
    ff_effects_max: c_ulong,
}
```

If sleeping with a long time, `cat /proc/bus/input/devices` will print an invalid device name.
And sometimes writing uinput file results in `Invalid argument`(errcode 22).

It may be better to be:
``` rust
/// uinput types
#[repr(C)]
struct UInputSetup {
    id: InputId,
    name: [i8, 80],
    ff_effects_max: c_ulong,
}
```

as the original definition in `/usr/include/linux/uinput.h` is:
``` C
#define UINPUT_MAX_NAME_SIZE    80
struct uinput_setup {
        struct input_id id;
        char name[UINPUT_MAX_NAME_SIZE];
        __u32 ff_effects_max;
};
```

The value may be assigned somehow like [`evdev`](https://github.com/emberian/evdev/blob/722052c7b1f2dca68f1e2d4f0eb774f70aaaacd7/src/uinput.rs#L115) do.

**Comment by emrebicer** [comment]
@fufesou Thanks for reporting this issue and the insights. I have committed a fix to the [dev](https://github.com/emrebicer/mouce/tree/dev) branch, I think it solves the issue. If you can confirm it I can merge to the master branch and make a new release on crates.io.

**Comment by fufesou** [comment]
I've tested on Ubuntu 22.04. The dev branch works well now.
